baseURL = "https://hugo-u39205.vm.elestio.app"
languageCode = "ja"
defaultContentLanguage = "ja"
title = "AI対応高機能サイト構築サービス - 株式会社インターワーク"

[params]
  author = "株式会社インターワーク"
  description = "AIに対応した高機能サイト構築サービス - 自動記事作成から、AIチャットボット"
  
[[menu.main]]
  name = "ホーム" 
  url = "/"
  weight = 1

[[menu.main]]
  name = "ブログ"
  url = "/blog/"
  weight = 2

[[menu.main]]
  name = "お問い合わせ"
  url = "/contact"
  weight = 3

[[menu.main]]
  name = "サポートポータル"
  url = "/faq"
  weight = 4

theme = "hugo-universal-theme"
