baseURL = "https://hugo-u39205.vm.elestio.app"
languageCode = "ja"
defaultContentLanguage = "ja"
title = "株式会社インターワーク"

[params]
  author = "株式会社インターワーク"
  description = "高機能サイト構築サービス"
  
[[menu.main]]
  name = "ホーム" 
  url = "/"
  weight = 1

[[menu.main]]
  name = "ブログ"
  url = "/blog/"
  weight = 2

[[menu.main]]
  name = "お問い合わせ"
  url = "/contact"
  weight = 3
theme = "hugo-universal-theme"
